version: "3.9"
services:
  database:
    container_name: database
    image: postgres:alpine3.15
    ports:
      - "5432:5432"
    hostname: postgresql
    environment:
      POSTGRES_PASSWORD: pa$$word
      POSTGRES_DB: mockify

  server:
    container_name: server
    depends_on: [database]
    image: bartlomiejgora/mockify
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgresql:5432/mockify"
      USER_NAME: postgres
      PASSWORD: pa$$word
