YAML 1.2
---
server:
  port: 8080
spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${USER_NAME}
    password: ${PASSWORD}
    hikari.max-lifetime: 600000
  
logging:
  file:
    name: Mockify.log
  logback:
    rollingpolicy:
      max-file-size: 5MB

