YAML 1.2
---

server:
  port: 8080
spring:
  sql:
    init:
      platform: h2
  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver

logging:
  file:
    name: Mockify.log
  logback:
    rollingpolicy:
      max-file-size: 5MB