YAML 1.2
---

server:
  port: 8080
spring:
  datasource:
    url: jdbc:tc:postgresql:11.1:///integration-tests-db
    hikari:
      max-lifetime: 600000
      driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

logging:
  file:
    name: Mockify.log
  logback:
    rollingpolicy:
      max-file-size: 5MB