scrape_configs:
    - job_name: 'spring'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
      - targets: ['localhost:8080']
remote_write:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
      basic_auth:
       username: "33706"
       password: eyJrIjoiZmEwOTY3ZGNlNDcwZTY4NTU2NjM5MzJjMGRkZjJlNDUwNDJhNDgyYyIsIm4iOiJNb2NraWZ5IiwiaWQiOjQ1ODYwMX0=